# Generated by Django 4.2.4 on 2023-11-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_scrape',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='haloUsername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
