# Generated by Django 4.2.4 on 2023-12-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='haloUsername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
