# Generated by Django 4.2.4 on 2023-12-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamertag', models.CharField(max_length=100)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('kd_ratio', models.FloatField()),
                ('assists', models.IntegerField()),
                ('headshots', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('damage_dealt', models.IntegerField()),
                ('damage_taken', models.IntegerField()),
                ('timeScraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
